http:
  listener:
    host: "localhost"
    port: "9083"
  requester:
    FastGo:
      host: "localhost"
      port: "9082"
      routespath: "/fastGocall/{serviceType}"
      schedulepath: "/fastGocall/{serviceType}" 
    TravelOnTip:
      host: "localhost"
      port: "9082"
      routespath: "/TravelOnTip/{serviceType}"
      schedulepath: "/TravelOnTip/{serviceType}"    
    
   